config/routes.rb
MyTest::Application.routes.draw do
  resources :dupadupas

  resources :child_dupa2s

  resources :child_dupas

  resources :dupas

  get "actrion1/action2"

end

app/models/dupa.rb
class Dupa < ActiveRecord::Base
end

app/controllers/dupas_controller.rb
class DupasController < ApplicationController
  # GET /dupas
  # GET /dupas.xml
  def index
    @dupas = Dupa.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dupas }
    end
  end

  # GET /dupas/1
  # GET /dupas/1.xml
  def show
    @dupa = Dupa.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dupa }
    end
  end

  # GET /dupas/new
  # GET /dupas/new.xml
  def new
    @dupa = Dupa.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dupa }
    end
  end

  # GET /dupas/1/edit
  def edit
    @dupa = Dupa.find(params[:id])
  end

  # POST /dupas
  # POST /dupas.xml
  def create
    @dupa = Dupa.new(params[:dupa])

    respond_to do |format|
      if @dupa.save
        format.html { redirect_to(@dupa, :notice => 'Dupa was successfully created.') }
        format.xml  { render :xml => @dupa, :status => :created, :location => @dupa }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dupa.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dupas/1
  # PUT /dupas/1.xml
  def update
    @dupa = Dupa.find(params[:id])

    respond_to do |format|
      if @dupa.update_attributes(params[:dupa])
        format.html { redirect_to(@dupa, :notice => 'Dupa was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dupa.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dupas/1
  # DELETE /dupas/1.xml
  def destroy
    @dupa = Dupa.find(params[:id])
    @dupa.destroy

    respond_to do |format|
      format.html { redirect_to(dupas_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/dupas_helper.rb
module DupasHelper
end

app/views/dupas/_form.html.erb
<%= form_for(@dupa) do |f| %>
  <% if @dupa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dupa.errors.count, "error") %> prohibited this dupa from being saved:</h2>

      <ul>
      <% @dupa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :memo %><br />
    <%= f.text_area :memo %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dupas/edit.html.erb
<h1>Editing dupa</h1>

<%= render 'form' %>

<%= link_to 'Show', @dupa %> |
<%= link_to 'Back', dupas_path %>

app/views/dupas/index.html.erb
<h1>Listing dupas</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Memo</th>
    <th>Number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dupas.each do |dupa| %>
  <tr>
    <td><%= dupa.name %></td>
    <td><%= dupa.memo %></td>
    <td><%= dupa.number %></td>
    <td><%= link_to 'Show', dupa %></td>
    <td><%= link_to 'Edit', edit_dupa_path(dupa) %></td>
    <td><%= link_to 'Destroy', dupa, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dupa', new_dupa_path %>

app/views/dupas/new.html.erb
<h1>New dupa</h1>

<%= render 'form' %>

<%= link_to 'Back', dupas_path %>

app/views/dupas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @dupa.name %>
</p>

<p>
  <b>Memo:</b>
  <%= @dupa.memo %>
</p>

<p>
  <b>Number:</b>
  <%= @dupa.number %>
</p>


<%= link_to 'Edit', edit_dupa_path(@dupa) %> |
<%= link_to 'Back', dupas_path %>