config/routes.rb
MyTest::Application.routes.draw do
  resources :dupadupas

  resources :child_dupa2s

  resources :child_dupas

  resources :dupas

  get "actrion1/action2"

end

app/models/child_dupa.rb
class ChildDupa < Dupa
end

app/controllers/child_dupas_controller.rb
class ChildDupasController < ApplicationController
  # GET /child_dupas
  # GET /child_dupas.xml
  def index
    @child_dupas = ChildDupa.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @child_dupas }
    end
  end

  # GET /child_dupas/1
  # GET /child_dupas/1.xml
  def show
    @child_dupa = ChildDupa.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @child_dupa }
    end
  end

  # GET /child_dupas/new
  # GET /child_dupas/new.xml
  def new
    @child_dupa = ChildDupa.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @child_dupa }
    end
  end

  # GET /child_dupas/1/edit
  def edit
    @child_dupa = ChildDupa.find(params[:id])
  end

  # POST /child_dupas
  # POST /child_dupas.xml
  def create
    @child_dupa = ChildDupa.new(params[:child_dupa])

    respond_to do |format|
      if @child_dupa.save
        format.html { redirect_to(@child_dupa, :notice => 'Child dupa was successfully created.') }
        format.xml  { render :xml => @child_dupa, :status => :created, :location => @child_dupa }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @child_dupa.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /child_dupas/1
  # PUT /child_dupas/1.xml
  def update
    @child_dupa = ChildDupa.find(params[:id])

    respond_to do |format|
      if @child_dupa.update_attributes(params[:child_dupa])
        format.html { redirect_to(@child_dupa, :notice => 'Child dupa was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @child_dupa.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /child_dupas/1
  # DELETE /child_dupas/1.xml
  def destroy
    @child_dupa = ChildDupa.find(params[:id])
    @child_dupa.destroy

    respond_to do |format|
      format.html { redirect_to(child_dupas_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/child_dupas_helper.rb
module ChildDupasHelper
end

app/views/child_dupas/_form.html.erb
<%= form_for(@child_dupa) do |f| %>
  <% if @child_dupa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@child_dupa.errors.count, "error") %> prohibited this child_dupa from being saved:</h2>

      <ul>
      <% @child_dupa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/child_dupas/edit.html.erb
<h1>Editing child_dupa</h1>

<%= render 'form' %>

<%= link_to 'Show', @child_dupa %> |
<%= link_to 'Back', child_dupas_path %>

app/views/child_dupas/index.html.erb
<h1>Listing child_dupas</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @child_dupas.each do |child_dupa| %>
  <tr>
    <td><%= child_dupa.name %></td>
    <td><%= child_dupa.memo %></td>
    <td><%= child_dupa.number %></td> 
    <td><%= link_to 'Show', child_dupa %></td>
    <td><%= link_to 'Edit', edit_child_dupa_path(child_dupa) %></td>
    <td><%= link_to 'Destroy', child_dupa, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Child dupa', new_child_dupa_path %>

app/views/child_dupas/new.html.erb
<h1>New child_dupa</h1>

<%= render 'form' %>

<%= link_to 'Back', child_dupas_path %>

app/views/child_dupas/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_child_dupa_path(@child_dupa) %> |
<%= link_to 'Back', child_dupas_path %>