config/routes.rb
MyTest::Application.routes.draw do
  resources :dupadupas

  resources :child_dupa2s

  resources :child_dupas

  resources :dupas

  get "actrion1/action2"

end

app/models/dupadupa.rb
class Dupadupa < ActiveRecord::Base
end

app/controllers/dupadupas_controller.rb
class DupadupasController < ApplicationController
  # GET /dupadupas
  # GET /dupadupas.xml
  def index
    @dupadupas = Dupadupa.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dupadupas }
    end
  end

  # GET /dupadupas/1
  # GET /dupadupas/1.xml
  def show
    @dupadupa = Dupadupa.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dupadupa }
    end
  end

  # GET /dupadupas/new
  # GET /dupadupas/new.xml
  def new
    @dupadupa = Dupadupa.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dupadupa }
    end
  end

  # GET /dupadupas/1/edit
  def edit
    @dupadupa = Dupadupa.find(params[:id])
  end

  # POST /dupadupas
  # POST /dupadupas.xml
  def create
    @dupadupa = Dupadupa.new(params[:dupadupa])

    respond_to do |format|
      if @dupadupa.save
        format.html { redirect_to(@dupadupa, :notice => 'Dupadupa was successfully created.') }
        format.xml  { render :xml => @dupadupa, :status => :created, :location => @dupadupa }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dupadupa.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dupadupas/1
  # PUT /dupadupas/1.xml
  def update
    @dupadupa = Dupadupa.find(params[:id])

    respond_to do |format|
      if @dupadupa.update_attributes(params[:dupadupa])
        format.html { redirect_to(@dupadupa, :notice => 'Dupadupa was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dupadupa.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dupadupas/1
  # DELETE /dupadupas/1.xml
  def destroy
    @dupadupa = Dupadupa.find(params[:id])
    @dupadupa.destroy

    respond_to do |format|
      format.html { redirect_to(dupadupas_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/dupadupas_helper.rb
module DupadupasHelper
end

app/views/dupadupas/_form.html.erb
<%= form_for(@dupadupa) do |f| %>
  <% if @dupadupa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dupadupa.errors.count, "error") %> prohibited this dupadupa from being saved:</h2>

      <ul>
      <% @dupadupa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dupadupas/edit.html.erb
<h1>Editing dupadupa</h1>

<%= render 'form' %>

<%= link_to 'Show', @dupadupa %> |
<%= link_to 'Back', dupadupas_path %>

app/views/dupadupas/index.html.erb
<h1>Listing dupadupas</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dupadupas.each do |dupadupa| %>
  <tr>
    <td><%= dupadupa.title %></td>
    <td><%= dupadupa.message %></td>
    <td><%= link_to 'Show', dupadupa %></td>
    <td><%= link_to 'Edit', edit_dupadupa_path(dupadupa) %></td>
    <td><%= link_to 'Destroy', dupadupa, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dupadupa', new_dupadupa_path %>

app/views/dupadupas/new.html.erb
<h1>New dupadupa</h1>

<%= render 'form' %>

<%= link_to 'Back', dupadupas_path %>

app/views/dupadupas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @dupadupa.title %>
</p>

<p>
  <b>Message:</b>
  <%= @dupadupa.message %>
</p>


<%= link_to 'Edit', edit_dupadupa_path(@dupadupa) %> |
<%= link_to 'Back', dupadupas_path %>